services:
  - type: web
    name: telegram-mtproxy
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: PROXY_SECRET
        value: your_32char_secret_here
      - key: PROXY_PORT
        value: "10000"
      - key: PROXY_AD_TAG
        value: your_ad_tag_from_mtproxybot
